"=========================
"Configurations
"=========================
syntax enable
set autoindent
set copyindent
set shiftwidth=4
set shiftround
set number
set relativenumber
set nowrap
set cursorline
"set cursorcolumn
set expandtab

"tab completion list on command mode
set wildmenu

"show key strokes on status bar
set showcmd

"ignore case only if search is in lowercase
set ignorecase
set smartcase

"use plugins and key mappings depending on file type
filetype plugin indent on

"insert tabs on the start of a line according to shiftwidth, not tabstop
set smarttab

"allow for :e to open new buffer without saving the previous one
set hidden

"highlight searches and double Esc to deselect
set incsearch
set hlsearch
nnoremap <silent> <Esc><Esc> :nohlsearch<Bar>:echo<CR>

"highlight non-ascii character
syntax match nonascii "[^\x00-\x7F]"
highlight nonascii guibg=Red ctermbg=6*

autocmd bufwritepre * :FixWhitespace

"tab space size
set ts=4

"auto source .vimrc after save
autocmd! bufwritepost .vimrc source %

"Save to clipboard
set clipboard=unnamed

"highligth text after 120 characters
match ErrorMsg '\%>120v.\+'

"avoid auto colapse of functions
set foldlevel=99

"force vim-airline to show on single file
set laststatus=2

"focus on new split window
set splitbelow
set splitright

"fix backspace on gvim
set backspace=indent,eol,start

"============
"Color Scheme
"============
set background=dark
set t_Co=256

colorscheme onedark
"colorscheme gruvbox
"colorscheme zenburn
"colorscheme Tomorrow-Night
"colorscheme apprentice
"colorscheme bubblegum
"colorscheme bvemu
"colorscheme blueprint
"colorscheme bensday

"let g:airline_theme='base16'
"let g:airline_theme='tomorrow'
"let g:airline_theme='zenburn'

"====================
"CtrlP Configurations
"====================
set wildignore+=*/target/*,*/node_modules/*

"tmux will send xterm-style keys when its xterm-keys option is on
if &term =~ '^screen'
    execute "set <xUp>=\e[1;*A"
    execute "set <xDown>=\e[1;*B"
    execute "set <xRight>=\e[1;*C"
    execute "set <xLeft>=\e[1;*D"
endif
